# Generated by Django 6.0.6 on 2026-06-25 10:08

import django.db.models.deletion
import papers.models
import papers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Software Engineering, Financial Accounting",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="e.g. CS501 (Optional)",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="QuestionPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.CharField(
                        choices=[
                            ("BSC", "Bachelor of Science (B.Sc)"),
                            ("MSC", "Master of Science (M.Sc)"),
                        ],
                        help_text="Select the degree/course",
                        max_length=20,
                    ),
                ),
                (
                    "year",
                    models.IntegerField(help_text="Enter the exam year (e.g. 2024)"),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("SEM1", "Semester 1"),
                            ("SEM2", "Semester 2"),
                            ("SEM3", "Semester 3"),
                            ("SEM4", "Semester 4"),
                            ("SEM5", "Semester 5"),
                            ("SEM6", "Semester 6"),
                        ],
                        help_text="Select the semester",
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Upload the question paper (PDF format only, max 10MB)",
                        upload_to=papers.models.question_paper_upload_path,
                        validators=[papers.validators.validate_pdf_file],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this paper is approved to display on the public listing.",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="Select the subject",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="papers",
                        to="papers.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "semester", "subject"],
            },
        ),
    ]
