# Generated by Django 6.0.6 on 2026-06-25 11:53

import django.db.models.deletion
import papers.models
import papers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. Calculus Unit 1, Organic Chemistry notes",
                        max_length=200,
                    ),
                ),
                (
                    "course",
                    models.CharField(
                        choices=[
                            ("BSC", "Bachelor of Science (B.Sc)"),
                            ("MSC", "Master of Science (M.Sc)"),
                        ],
                        help_text="Select the course",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Upload notes in PDF format (max 10MB)",
                        upload_to=papers.models.subject_note_upload_path,
                        validators=[papers.validators.validate_pdf_file],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this note is approved to display on the public listing.",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        help_text="Select the subject",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="papers.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["subject", "title"],
            },
        ),
    ]
