# Generated by Django 6.0.6 on 2026-06-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0002_subjectnote"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="User's full name", max_length=100),
                ),
                (
                    "email",
                    models.EmailField(help_text="User's email address", max_length=254),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Subject of the message/report", max_length=200
                    ),
                ),
                ("message", models.TextField(help_text="Detailed message content")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_resolved",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this issue has been resolved by an administrator.",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
